
<div id="topPictureContainer">
	<img src="<?php echo $this->getViewFileUrl('images/collection-performance.jpg'); ?>">
</div>
<div id="content1" >
   <img src="<?php echo $this->getViewFileUrl('images/ProductCate_01.jpg'); ?>" class="lazyload w-100" alt="">
    <img src="<?php echo $this->getViewFileUrl('images/ProductCate_02.jpg'); ?>" class="lazyload w-100" alt="">
    <img src="<?php echo $this->getViewFileUrl('images/ProductCate_03.jpg'); ?>" class="lazyload w-100" alt="">
</div>
<div id="content2">
    <img src="<?php echo $this->getViewFileUrl('images/ProductCate_04.jpg'); ?>" class="lazyload w-100" alt="">
    <img src="<?php echo $this->getViewFileUrl('images/ProductCate_05.jpg'); ?>" class="lazyload w-100" alt="">
    <img src="<?php echo $this->getViewFileUrl('images/ProductCate_06.jpg'); ?>" class="lazyload w-100" alt="">

</div>
<div class="homepage-bar mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4" style="text-align:center;">
                <div class="text-area">
                    <h4> FREE SHIPPING &amp; RETURN</h4>
                    <p><i class="fa fa-car" style="font-size:30px;"></i> Free shipping on all orders over $99.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4" style="text-align:center;">
                <div class="text-area"><h4>MONEY BACK GUARANTEE</h4>
                    <p><i class="fa fa-car" style="font-size:30px;"></i> 100% money back guarantee.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4" style="text-align:center;">
                <div class="text-area"><h4>ONLINE SUPPORT 24/7</h4>
                    <p><i class="fa fa-cog" style="font-size:30px;"></i> Lorem ipsum dolor sit amet.</p>
                </div>
            </div>
        </div>
    </div>
</div>